# Requirement: Dependency Management Automation
# Location: Technical Specification/System Design/Development Environment
# Description: Ensures that dependencies across the project are kept up-to-date with the latest secure and compatible versions.

version: 2
updates:
  # Backend npm dependencies
  - package-ecosystem: "npm"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
    # Auto-merge configuration
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
    # Auto-merge configuration  
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Backend Docker dependencies
  - package-ecosystem: "docker"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
    # Auto-merge configuration
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "docker"
      - "backend"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"

  # Frontend Docker dependencies
  - package-ecosystem: "docker"
    directory: "/src/web"
    schedule:
      interval: "weekly"
    # Auto-merge configuration
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels:
      - "dependencies" 
      - "docker"
      - "frontend"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"