# Kubernetes Version: 1.26.x
# Purpose: Define ServiceAccounts for pod identity management across different environments
# Requirements Addressed:
# - Pod Identity Management (Technical Specification/System Architecture/Deployment Architecture):
#   ServiceAccounts provide identities for pods to securely interact with the Kubernetes API
#   and other resources, ensuring proper access control and security.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-service-account
  namespace: default
  labels:
    app: platform
    environment: production
  annotations:
    description: "ServiceAccount for pods running in production environment"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: staging-service-account
  namespace: staging
  labels:
    app: platform
    environment: staging
  annotations:
    description: "ServiceAccount for pods running in staging environment"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: development-service-account
  namespace: development
  labels:
    app: platform
    environment: development
  annotations:
    description: "ServiceAccount for pods running in development environment"